### ISSUE TITLE
`globalScope.__defineGeneric` is not a function

### ISSUE THREAD

**Issue by e1cb4ac37s** [flow-typed/eslint-plugin-ft-flow#49] opened 2024-01-25 16:44 UTC
# `globalScope.__defineGeneric` is not a funtion
Hello. **What problem do I try to solve**: we try to migrate our out-of-date flow to the latest version, and on the way installed `ft-flow` to lint it. We have `no-undef` rule, and need to override it for flow internal types, i.e. `$Values<...>`, `$Keys<...>`, ..., because they conflict with eslint's `no-undef` now.
I'm trying to add `ft-flow` to `.eslintrs.js`, which kinda works until I start adding rules beyond recommended extension. My config (relevant parts, I guess):

```javascript
module.exports = {
  parser: 'hermes-eslint',
  parserOptions: {
    ecmaVersion: 9,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
    babelOptions: {
      configFile: path.resolve(__dirname, './babel.config.js'),
    },
  },
  extends: [
    // ...
    'plugin:ft-flow/recommended'
  ],
  plugins: [
    'ft-flow',
    // ...
  ],
  env: {
    browser: true,
    jquery: true,
    node: true,
    jest: true,
    es6: true,
  },
  root: true,
  rules: {
    'ft-flow/use-flow-type': 1,
    'ft-flow/define-flow-type': 1, // this rule breaks
    // ...
  },
  // ...
}
```

The line of code where I get the error (I guess, `$Values<...>` breaks it)
```javascript
export type ResourceType = $Values<typeof RESOURCE_TYPES>
```

```
ESLint: 8.56.0

TypeError: globalScope.__defineGeneric is not a function
Occurred while linting [some js file here]
Rule: "ft-flow/define-flow-type"
    at makeDefined (PATH/node_modules/eslint-plugin-ft-flow/dist/rules/defineFlowType.js:28:21)
    at GenericTypeAnnotation (PATH/node_modules/eslint-plugin-ft-flow/dist/rules/defineFlowType.js:67:9)
    at PATH/node_modules/eslint/lib/linter/timing.js:141:28
    at ruleErrorHandler (PATH/node_modules/eslint/lib/linter/linter.js:1076:28)
    at PATH/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (PATH/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (PATH/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (PATH/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (PATH/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

There is similar [issue](https://github.com/gajus/eslint-plugin-flowtype/issues/524) in your legacy (right?) project, but no solutions provided whatsoever. What can I do? Or maybe this is a bug? Thank you in advance.

**Comment by Brianzchen** [comment] 2024-01-27 02:38
Thanks for raising this issue. At first glance it seems to be because `__defineGeneric` object does not exist in the `hermes-eslint` parser so I expect it should work with `@babel/eslint-parser` and as a result it's throwing.

But because with flow you should use `hermes-eslint` to parse the syntax correctly we'll have to find a solution for you. I'll keep digging to find what the equivalent with hermes would be.

> Do note that flow team recommended that this rule isn't necessary anymore hence why we didn't test for this case

**Comment by Brianzchen** [comment] 2024-01-27 08:43
Have raised an issue with hermes team. Lets see if they come back with anything useful before I cont my investigation. Otherwise I'll need to understand what that function did in the beginning to find a suitable replacement function

**Comment by Brianzchen** [comment] 2024-01-27 23:31
^ Merged a fix. Please give a go with v3.0.3 and let me know if it works 🙏

**Comment by Brianzchen** [comment] 2024-01-29 20:36
:/ hmm I'll need to reproduce it in tests to find a solution. The change I made was to `define-flow-type` only and I suspect that when I inject the global variable it's missing something causing the next rule to fail.
```
    'ft-flow/define-flow-type': 1, // (1)
    'ft-flow/use-flow-type': 1, // (2)
```

For some more info

1. Could you share the line or token that fails to be parsed causing this error?
2. Is it when both rules are in use or only one?
3. What happens if you only one of `define-flow-type` or `use-flow-type`?

**Comment by e1cb4ac37s** [comment] 2024-01-30 06:57
1. here it is:
    ```js
    // @flow
    
    import { Api } from 'services/api' // <- this one
    ```
    this looks like it breaks on **a first line of the first flow-tagged file**, as deleting this line moves an error to the next non-empty one, deleting the file moves error to the next file, first non-empty line.
3. Indeed, commenting them out one-by-one shows that only `define-flow-type` breaks `no-unused-vars`, `use-flow-type` is ok.

**Comment by Brianzchen** [comment] 2024-02-04 01:57
Great I was able to reproduce this, turns out we never had a test against `no-unused-vars` and only tested `no-undef` and `no-use-before-define`.

**Comment by Brianzchen** [comment] 2024-02-04 10:00
@e1cb4ac37s can you try `3.0.4-alpha-0`. I removed something that seemed unnecessary and was causing issues. It's throwing the unused errors correctly but need to spend more time getting the tests to play nicely together before I can merge and make an official release

**Comment by Brianzchen** [comment] 2024-02-06 04:33
Thanks for validating @short-dsb. I'll work on getting my tests working and publish an official release this weekend... Unless someone finds more problems 😨

**Closed** 2024-02-11 01:17 UTC
